# -*- coding: utf-8 -*-
"""Data Pre Processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/IBM-EPBL/IBM-Project-27413-1660056032/blob/main/Project%20Development%20Phase/Sprint%201/Data%20Pre%20Processing.ipynb

# DATA-PREPROCESSING
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

"""### READ THE DATASET """

#Import Dataset
ds=pd.read_csv("dataset_website.csv")
ds.head()

"""### HANDLING NULL VALUES """

#Analyzing the data using pandas and Checking if the dataset contains any Null values
ds.info()
ds.isnull().any() #no nullvalues

"""### SPLITTING THE DATA"""

#Splitting data as independent and dependent
#removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)

#Splitting data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)